name: GCP Federation Test
on: [push]

permissions:
  contents: 'read'
  id-token: 'write' # REQUIRED for Federation

jobs:
  test-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/884973118859/locations/global/workloadIdentityPools/github-deployer/providers/github-provider'
          service_account: 'github-deployer@modern-water-477805-e3.iam.gserviceaccount.com'

      - name: 'List Buckets'
        run: gcloud storage ls
